[build]
  # Standard Next.js build command
  command = "npm run build"
  # Next.js builds output to the .next folder
  publish = ".next"
[[plugins]]
package = "@netlify/plugin-lighthouse"
[plugins.inputs.settings]
# Optionally run Lighthouse using a "desktop" configuration (defaults to "mobile")
preset = "desktop" 